import * as fs from 'fs';
import * as path from 'path';
import { SecurityIssue, ScanResult } from '../config/types';

export function generateHTMLReport(result: ScanResult, outputPath: string): void {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ShieldTS Security Report</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'Courier New', Courier, monospace;
      background: #e0e0e0;
      padding: 20px;
      line-height: 1.6;
    }
    .container { max-width: 1200px; margin: 0 auto; background: white; padding: 40px; border: 3px solid #000; }
    h1 { color: #000; margin-bottom: 10px; font-weight: bold; text-transform: uppercase; border-bottom: 2px solid #000; padding-bottom: 10px; }
    .summary {
      background: ${result.passed ? '#d4edda' : '#f8d7da'};
      color: ${result.passed ? '#155724' : '#721c24'};
      padding: 20px;
      border-radius: 6px;
      margin: 20px 0;
      border-left: 4px solid ${result.passed ? '#28a745' : '#dc3545'};
    }
    .stats { display: flex; gap: 20px; margin: 20px 0; }
    .stat { background: #f8f9fa; padding: 15px; border-radius: 6px; flex: 1; }
    .stat-value { font-size: 2rem; font-weight: bold; color: #007bff; }
    .stat-label { color: #6c757d; font-size: 0.9rem; }
    .issue {
      border-left: 4px solid #dc3545;
      background: #fff5f5;
      padding: 20px;
      margin: 20px 0;
      border-radius: 4px;
    }
    .issue.warning { border-left-color: #ffc107; background: #fffbf0; }
    .issue-header { display: flex; justify-content: space-between; align-items: start; margin-bottom: 10px; }
    .issue-title { font-weight: bold; color: #dc3545; font-size: 1.1rem; }
    .issue.warning .issue-title { color: #856404; }
    .badge {
      display: inline-block;
      padding: 4px 12px;
      border-radius: 12px;
      font-size: 0.8rem;
      font-weight: bold;
      text-transform: uppercase;
    }
    .badge-error { background: #dc3545; color: white; }
    .badge-warning { background: #ffc107; color: #000; }
    .location { color: #6c757d; font-size: 0.9rem; margin-bottom: 10px; }
    .snippet {
      background: #f8f9fa;
      padding: 15px;
      border-radius: 4px;
      font-family: 'Monaco', 'Menlo', 'Courier New', monospace;
      font-size: 0.9rem;
      overflow-x: auto;
      margin: 10px 0;
    }
    .education {
      background: #e7f3ff;
      border-left: 4px solid #007bff;
      padding: 15px;
      margin-top: 15px;
      border-radius: 4px;
    }
    .education h4 { color: #004085; margin-bottom: 8px; }
    .education p { color: #004085; }
    .education a {
      color: #007bff;
      text-decoration: none;
      font-weight: 500;
      display: inline-block;
      margin-top: 8px;
    }
    .education a:hover { text-decoration: underline; }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #dee2e6;
      color: #6c757d;
      text-align: center;
    }
    .file-group { margin: 30px 0; }
    .file-name {
      background: #343a40;
      color: white;
      padding: 10px 15px;
      border-radius: 4px;
      font-family: monospace;
      margin-bottom: 10px;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>=== ShieldTS Security Report ===</h1>
    <p style="color: #666;">Generated on ${new Date().toLocaleString()}</p>

    <div class="summary">
      <h2>${result.passed ? '[PASS] No Security Issues Found' : '[FAIL] Security Issues Detected'}</h2>
      <p>${result.passed
        ? 'Your codebase passed all security checks.'
        : 'Your build has been blocked due to security vulnerabilities. Please review and fix the issues below.'
      }</p>
    </div>

    <div class="stats">
      <div class="stat">
        <div class="stat-value">${result.filesScanned}</div>
        <div class="stat-label">Files Scanned</div>
      </div>
      <div class="stat">
        <div class="stat-value" style="color: #dc3545;">${result.issues.filter(i => i.severity === 'error').length}</div>
        <div class="stat-label">Errors</div>
      </div>
      <div class="stat">
        <div class="stat-value" style="color: #ffc107;">${result.issues.filter(i => i.severity === 'warning').length}</div>
        <div class="stat-label">Warnings</div>
      </div>
    </div>

    ${result.passed ? '' : generateIssuesHTML(result.issues)}

    <div class="footer">
      <p>Generated by <strong>ShieldTS</strong> - TypeScript Security Scanner</p>
      <p style="margin-top: 10px;">
        <a href="https://owasp.org/www-project-top-ten/" target="_blank">Learn more about OWASP Top 10</a>
      </p>
    </div>
  </div>
</body>
</html>`;

  fs.writeFileSync(outputPath, html, 'utf-8');
}

function generateIssuesHTML(issues: SecurityIssue[]): string {
  // Group by file
  const issuesByFile = new Map<string, SecurityIssue[]>();
  for (const issue of issues) {
    if (!issuesByFile.has(issue.file)) {
      issuesByFile.set(issue.file, []);
    }
    issuesByFile.get(issue.file)!.push(issue);
  }

  let html = '<h2 style="margin-top: 40px;">Issues Found</h2>';

  for (const [file, fileIssues] of issuesByFile) {
    html += `
      <div class="file-group">
        <div class="file-name">${escapeHtml(file)}</div>
        ${fileIssues.map(issue => `
          <div class="issue ${issue.severity}">
            <div class="issue-header">
              <div class="issue-title">${escapeHtml(issue.message)}</div>
              <span class="badge badge-${issue.severity}">${issue.severity}</span>
            </div>
            <div class="location">Location: Line ${issue.line}, Column ${issue.column}${issue.provider ? ` | Provider: ${issue.provider}` : ''}</div>
            <div class="snippet">${escapeHtml(issue.snippet)}</div>
            ${issue.educationalContent ? `
              <div class="education">
                <h4>Why is this a problem?</h4>
                <p>${escapeHtml(issue.educationalContent)}</p>
                ${issue.bestPracticeLink ? `<a href="${issue.bestPracticeLink}" target="_blank">Learn more →</a>` : ''}
              </div>
            ` : ''}
          </div>
        `).join('')}
      </div>
    `;
  }

  return html;
}

function escapeHtml(text: string): string {
  const map: Record<string, string> = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;'
  };
  return text.replace(/[&<>"']/g, m => map[m]);
}
